# Generated by Django 6.1 on 2026-08-20 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmProfitCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop", models.CharField(max_length=100)),
                ("area", models.FloatField(help_text="Area in acres")),
                ("seed_cost", models.FloatField(default=0)),
                ("fertilizer_cost", models.FloatField(default=0)),
                ("pesticide_cost", models.FloatField(default=0)),
                ("labour_cost", models.FloatField(default=0)),
                ("irrigation_cost", models.FloatField(default=0)),
                ("machinery_cost", models.FloatField(default=0)),
                ("other_cost", models.FloatField(default=0)),
                (
                    "expected_yield",
                    models.FloatField(help_text="Expected yield in quintals"),
                ),
                (
                    "selling_price",
                    models.FloatField(help_text="Expected selling price per quintal"),
                ),
                ("total_cost", models.FloatField(default=0)),
                ("expected_revenue", models.FloatField(default=0)),
                ("expected_profit", models.FloatField(default=0)),
                ("roi", models.FloatField(default=0)),
                ("break_even_price", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
