# Generated by Django 5.2.17 on 2026-09-23 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("tractor", "Tractor"),
                            ("rotavator", "Rotavator"),
                            ("seed_drill", "Seed Drill"),
                            ("sprayer", "Sprayer"),
                            ("harvester", "Harvester"),
                            ("cultivator", "Cultivator"),
                            ("thresher", "Thresher"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model_number", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(max_length=200)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(default="Uttar Pradesh", max_length=100)),
                (
                    "rent_type",
                    models.CharField(
                        choices=[
                            ("hour", "Per Hour"),
                            ("day", "Per Day"),
                            ("acre", "Per Acre"),
                        ],
                        default="day",
                        max_length=20,
                    ),
                ),
                ("rent_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "security_deposit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("operator_available", models.BooleanField(default=False)),
                ("delivery_available", models.BooleanField(default=False)),
                ("contact_number", models.CharField(blank=True, max_length=20)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="equipment/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("booked", "Booked"),
                            ("maintenance", "Maintenance"),
                            ("inactive", "Inactive"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("owner_response", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
