# Generated by Django 5.2.17 on 2026-10-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="acre_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="availability_note",
            field=models.CharField(
                blank=True,
                default="🟢 Live: Ready for instant dispatch",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="chc_hub_name",
            field=models.CharField(blank=True, default="Kisan CHC Hub", max_length=150),
        ),
        migrations.AddField(
            model_name="equipment",
            name="fuel_included",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="equipment",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="latitude",
            field=models.FloatField(blank=True, default=26.8467, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="longitude",
            field=models.FloatField(blank=True, default=80.9462, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=4.8, max_digits=3),
        ),
        migrations.AddField(
            model_name="equipment",
            name="total_trips",
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="equipment_type",
            field=models.CharField(
                choices=[
                    ("tractor", "Tractor (ट्रैक्टर)"),
                    ("rotavator", "Rotavator (रोटावेटर)"),
                    ("seed_drill", "Seed Drill / Super Seeder (सुपर सीडर)"),
                    ("sprayer", "Boom Sprayer (स्प्रेयर)"),
                    ("drone", "Agri Drone Sprayer (कृषि ड्रोन)"),
                    ("harvester", "Combine Harvester (कंबाइन हार्वेस्टर)"),
                    ("leveler", "Laser Land Leveler (लेजर लेवलर)"),
                    ("cultivator", "Cultivator / Plough (कल्टीवेटर)"),
                    ("thresher", "Multi-Crop Thresher (थ्रेशर)"),
                    ("pump", "Solar / Diesel Water Pump (पानी का पंप)"),
                    ("other", "Other Implements (अन्य उपकरण)"),
                ],
                max_length=30,
            ),
        ),
    ]
