# Generated by Django 6.1 on 2026-08-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FarmingTechnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("irrigation", "Smart Irrigation"),
                            ("fertilizer", "Smart Fertilization"),
                            ("pest", "Pest Management"),
                            ("monitoring", "Crop Monitoring"),
                            ("precision", "Precision Farming"),
                            ("drone", "Drone Technology"),
                            ("soil", "Soil Management"),
                            ("harvesting", "Smart Harvesting"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("short_description", models.TextField()),
                ("technology_used", models.CharField(blank=True, max_length=255)),
                (
                    "benefits",
                    models.TextField(help_text="Write each benefit on a new line."),
                ),
                (
                    "implementation",
                    models.TextField(
                        help_text="Explain how farmers can implement this technique."
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("estimated_cost", models.CharField(blank=True, max_length=100)),
                ("suitable_season", models.CharField(blank=True, max_length=150)),
                ("video_title", models.CharField(blank=True, max_length=200)),
                ("video_url", models.URLField(blank=True)),
                ("thumbnail_url", models.URLField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
    ]
