# Generated by Django 6.1 on 2026-08-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmerprofile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="farmerprofile",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="farmerprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("Farmer", "Farmer"),
                    ("Expert", "Expert"),
                    ("Admin", "Admin"),
                ],
                default="Farmer",
                max_length=20,
            ),
        ),
    ]
