# Generated by Django 6.1 on 2026-08-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "expert_type",
                    models.CharField(
                        choices=[
                            ("scientist", "Agricultural Scientist"),
                            ("researcher", "Agricultural Researcher"),
                            ("farmer", "Experienced Farmer"),
                            ("organization", "Agricultural Organization"),
                            ("company", "Agricultural Company"),
                            ("university", "Agricultural University"),
                            ("specialist", "Agriculture Specialist"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "organization",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("specialization", models.CharField(max_length=300)),
                (
                    "crops",
                    models.CharField(
                        blank=True,
                        help_text="Example: Rice, Wheat, Tomato",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "languages",
                    models.CharField(
                        blank=True,
                        help_text="Example: Hindi, English, Bengali",
                        max_length=300,
                        null=True,
                    ),
                ),
                ("experience_years", models.PositiveIntegerField(default=0)),
                ("about", models.TextField(blank=True, null=True)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="experts/"),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("official_profile", models.URLField(blank=True, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("pending", "Pending Verification"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
