# Generated by Django 6.1 on 2026-08-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MandiPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("market", models.CharField(max_length=150)),
                ("commodity", models.CharField(max_length=150)),
                ("variety", models.CharField(blank=True, max_length=150)),
                ("min_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("modal_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("arrival_date", models.DateField()),
            ],
            options={
                "ordering": ["-arrival_date"],
            },
        ),
    ]
