# Generated by Django 6.1 on 2026-08-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GovernmentScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("short_description", models.TextField()),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("income_support", "Income Support"),
                            ("insurance", "Crop Insurance"),
                            ("irrigation", "Irrigation"),
                            ("credit", "Agricultural Credit"),
                            ("mechanization", "Farm Mechanization"),
                            ("organic", "Organic Farming"),
                            ("marketing", "Agricultural Marketing"),
                            ("soil", "Soil & Fertility"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("benefits", models.TextField()),
                ("eligibility", models.TextField()),
                ("documents_required", models.TextField(blank=True, null=True)),
                ("state", models.CharField(default="All India", max_length=100)),
                ("min_land", models.FloatField(blank=True, null=True)),
                ("max_land", models.FloatField(blank=True, null=True)),
                ("min_age", models.PositiveIntegerField(blank=True, null=True)),
                ("max_age", models.PositiveIntegerField(blank=True, null=True)),
                ("official_url", models.URLField()),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
