# Generated by Django 5.2.17 on 2026-09-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("government_schemes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="governmentscheme",
            options={"ordering": ["title"]},
        ),
        migrations.RenameField(
            model_name="governmentscheme",
            old_name="active",
            new_name="is_active",
        ),
        migrations.RenameField(
            model_name="governmentscheme",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="governmentscheme",
            name="documents_required",
        ),
        migrations.RemoveField(
            model_name="governmentscheme",
            name="max_age",
        ),
        migrations.RemoveField(
            model_name="governmentscheme",
            name="max_land",
        ),
        migrations.RemoveField(
            model_name="governmentscheme",
            name="min_age",
        ),
        migrations.RemoveField(
            model_name="governmentscheme",
            name="min_land",
        ),
        migrations.RemoveField(
            model_name="governmentscheme",
            name="state",
        ),
        migrations.AddField(
            model_name="governmentscheme",
            name="application_process",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="governmentscheme",
            name="documents",
            field=models.TextField(
                blank=True, help_text="Write required documents on a new line."
            ),
        ),
        migrations.AddField(
            model_name="governmentscheme",
            name="helpline",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="governmentscheme",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name="governmentscheme",
            name="benefits",
            field=models.TextField(help_text="Write each benefit on a new line."),
        ),
        migrations.AlterField(
            model_name="governmentscheme",
            name="category",
            field=models.CharField(
                choices=[
                    ("income", "Income Support"),
                    ("insurance", "Crop Insurance"),
                    ("credit", "Credit & Finance"),
                    ("irrigation", "Irrigation"),
                    ("equipment", "Farm Equipment"),
                    ("soil", "Soil & Fertilizer"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="governmentscheme",
            name="eligibility",
            field=models.TextField(
                help_text="Write each eligibility condition on a new line."
            ),
        ),
        migrations.AlterField(
            model_name="governmentscheme",
            name="official_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="governmentscheme",
            name="short_description",
            field=models.CharField(max_length=500),
        ),
    ]
