# Generated by Django 5.2.17 on 2026-09-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("government_schemes", "0002_alter_governmentscheme_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="governmentscheme",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="governmentscheme",
            name="application_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="governmentscheme",
            name="crops",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="governmentscheme",
            name="district",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="governmentscheme",
            name="farmer_type",
            field=models.CharField(
                choices=[
                    ("any", "Any"),
                    ("small", "Small Farmer"),
                    ("marginal", "Marginal Farmer"),
                    ("tenant", "Tenant Farmer"),
                    ("landless", "Landless Farmer"),
                    ("all", "All Farmers"),
                ],
                default="any",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="governmentscheme",
            name="gender",
            field=models.CharField(
                choices=[
                    ("any", "Any"),
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                ],
                default="any",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="governmentscheme",
            name="last_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="governmentscheme",
            name="max_age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="governmentscheme",
            name="max_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="governmentscheme",
            name="max_land_area",
            field=models.FloatField(
                blank=True, help_text="Maximum land area in acres", null=True
            ),
        ),
        migrations.AddField(
            model_name="governmentscheme",
            name="min_age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="governmentscheme",
            name="min_land_area",
            field=models.FloatField(
                blank=True, help_text="Minimum land area in acres", null=True
            ),
        ),
        migrations.AddField(
            model_name="governmentscheme",
            name="seasons",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="governmentscheme",
            name="source_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="governmentscheme",
            name="state",
            field=models.CharField(default="All India", max_length=100),
        ),
        migrations.AddField(
            model_name="governmentscheme",
            name="valid_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="governmentscheme",
            name="valid_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="governmentscheme",
            name="verification_source",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="governmentscheme",
            name="benefits",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="governmentscheme",
            name="category",
            field=models.CharField(
                choices=[
                    ("income", "Income Support"),
                    ("insurance", "Crop Insurance"),
                    ("credit", "Credit"),
                    ("subsidy", "Subsidy"),
                    ("equipment", "Farm Equipment"),
                    ("irrigation", "Irrigation"),
                    ("education", "Education"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="governmentscheme",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="governmentscheme",
            name="documents",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="governmentscheme",
            name="eligibility",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="governmentscheme",
            name="short_description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="governmentscheme",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
