# Generated by Django 5.2.17 on 2026-09-23 13:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Land",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "land_type",
                    models.CharField(
                        choices=[
                            ("agricultural", "Agricultural"),
                            ("orchard", "Orchard"),
                            ("greenhouse", "Greenhouse"),
                            ("mixed", "Mixed Farming"),
                        ],
                        default="agricultural",
                        max_length=30,
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        choices=[
                            ("rent", "Rent"),
                            ("share", "Share"),
                            ("lease", "Lease"),
                        ],
                        default="share",
                        max_length=20,
                    ),
                ),
                ("village", models.CharField(max_length=120)),
                ("district", models.CharField(max_length=120)),
                ("state", models.CharField(max_length=120)),
                ("pincode", models.CharField(blank=True, max_length=10)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "total_area",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "available_area",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("soil_type", models.CharField(blank=True, max_length=100)),
                ("soil_description", models.TextField(blank=True)),
                ("suitable_crops", models.CharField(blank=True, max_length=400)),
                (
                    "water_source",
                    models.CharField(
                        choices=[
                            ("none", "No Water Source"),
                            ("borewell", "Borewell"),
                            ("canal", "Canal"),
                            ("tube_well", "Tube Well"),
                            ("rainwater", "Rainwater"),
                            ("multiple", "Multiple Sources"),
                        ],
                        default="none",
                        max_length=30,
                    ),
                ),
                ("electricity_available", models.BooleanField(default=False)),
                ("road_access", models.BooleanField(default=True)),
                (
                    "rent_per_acre_month",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "security_deposit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("minimum_duration_months", models.PositiveIntegerField(default=1)),
                ("maximum_duration_months", models.PositiveIntegerField(default=60)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="land_marketplace/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("occupied", "Occupied"),
                            ("closed", "Closed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="land_marketplace_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_verified", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LandImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="land_marketplace/gallery/")),
                ("is_primary", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "land",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="land_marketplace.land",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LandRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_area",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "duration_months",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("proposed_start_date", models.DateField()),
                ("message", models.TextField(blank=True)),
                (
                    "calculated_rent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "security_deposit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "total_estimated_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("owner_review", "Owner Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("owner_response", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "land",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="land_marketplace.land",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="land_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="land",
            index=models.Index(
                fields=["state", "district"], name="land_market_state_e468e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="land",
            index=models.Index(
                fields=["status", "listing_type"], name="land_market_status_1decf4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="land",
            index=models.Index(
                fields=["available_area"], name="land_market_availab_680278_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="land",
            constraint=models.CheckConstraint(
                condition=models.Q(("available_area__lte", models.F("total_area"))),
                name="available_area_lte_total_area",
            ),
        ),
        migrations.AddConstraint(
            model_name="landrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "owner_review", "approved"])
                ),
                fields=("land", "requester"),
                name="one_active_request_per_farmer_land",
            ),
        ),
    ]
