from datetime import date
from django.core.management.base import BaseCommand
from django.utils.text import slugify
from government_schemes.models import GovernmentScheme


SCHEMES_DATA = [
    {
        "title": "PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)",
        "slug": "pm-kisan",
        "short_description": "Direct income support of ₹6,000 per year provided in three equal installments of ₹2,000 directly into the bank accounts of farmer families.",
        "description": "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN) is a flagship Central Sector scheme launched by the Government of India to provide income support to all landholding farmer families across the country. The financial assistance supplements farmers' financial needs for procuring various agricultural inputs and domestic necessities. Payments are transferred seamlessly via Direct Benefit Transfer (DBT) directly into Aadhaar-seeded bank accounts.",
        "category": "income",
        "state": "All India",
        "farmer_type": "all",
        "min_age": 18,
        "max_age": 100,
        "gender": "any",
        "benefits": "• ₹6,000 per year directly transferred to bank accounts\n• Disbursed in 3 equal installments of ₹2,000 every 4 months (April-July, August-November, December-March)\n• 100% funded by Central Government with zero intermediary deduction\n• Financial relief for purchasing seeds, fertilizers, and addressing household emergencies",
        "eligibility": "• All landholder farmer families who have cultivable land in their names\n• Both small/marginal and large farmer families are eligible\n• Exclusion: Institutional landholders, serving/retired government officers/employees, income tax payees of last assessment year, and professionals (doctors, engineers, lawyers, CAs)",
        "documents": "• Aadhaar Card (mandatory)\n• Land Ownership Papers (Khatauni / Khasra / RoR record)\n• Bank Account details linked with Aadhaar & NPCI mapping\n• Active Mobile Number linked with Aadhaar",
        "application_process": "1. Online via PM-KISAN Portal (pmkisan.gov.in) under 'Farmers Corner' -> 'New Farmer Registration'.\n2. Enter Aadhaar number and State, select Rural or Urban Farmer.\n3. Fill in land details (Khata / Khasra numbers), bank account IFSC and upload land record.\n4. Complete e-KYC using OTP or biometric verification.\n5. Alternatively, visit your nearest Common Service Centre (CSC) or contact the local District Agricultural Officer.",
        "official_url": "https://pmkisan.gov.in/",
        "source_url": "https://agricoop.nic.in/en/pm-kisan",
        "helpline": "155261 / 1800-115-526 / 011-24300606",
        "verification_source": "Ministry of Agriculture & Farmers Welfare, GoI",
        "is_active": True,
    },
    {
        "title": "PMFBY (Pradhan Mantri Fasal Bima Yojana)",
        "slug": "pm-fasal-bima-yojana",
        "short_description": "Comprehensive, low-premium crop insurance protecting farmers against yield loss and crop damage from non-preventable natural risks.",
        "description": "Pradhan Mantri Fasal Bima Yojana (PMFBY) offers low-cost crop insurance coverage and financial support to farmers suffering crop loss or damage arising from unforeseen events like droughts, unseasonal heavy rains, floods, landslides, natural fires, pests, and diseases. It stabilizes farmer income and encourages adoption of progressive agricultural practices with satellite/drone backed damage assessment.",
        "category": "insurance",
        "state": "All India",
        "farmer_type": "all",
        "min_age": 18,
        "max_age": 100,
        "gender": "any",
        "benefits": "• Extremely low premium paid by farmers: Maximum 2.0% for Kharif food crops, 1.5% for Rabi food crops, and 5.0% for commercial/horticultural crops\n• Remainder premium subsidy shared 50:50 by Central and State Governments\n• Complete coverage from pre-sowing to post-harvest (up to 14 days after harvest for localized calamities)\n• Quick claim settlement directly into bank accounts via National Crop Insurance Portal (NCIP)",
        "eligibility": "• All farmers including sharecroppers and tenant farmers growing notified crops in notified areas\n• Open to both loanee farmers (holding KCC) and non-loanee farmers\n• Available across major cereals, millets, pulses, oilseeds, and annual commercial/horticultural crops",
        "documents": "• Aadhaar Card\n• Land Possession Certificate (LPC) or tenancy agreement/sowing declaration\n• Sowing Certificate or self-declaration stamped by Patwari/Village Accountant\n• Cancelled Cheque or Bank Passbook copy",
        "application_process": "1. Visit the National Crop Insurance Portal (pmfby.gov.in) or download the Crop Insurance Mobile App.\n2. Choose 'Apply for Crop Insurance as a Farmer' and login with your mobile number.\n3. Enter state, crop season, district, village, and survey/khasra numbers.\n4. Pay the nominal farmer share premium through UPI, Net Banking, or Debit Card.\n5. Can also be applied through authorized bank branches, Primary Agricultural Credit Societies (PACS), or CSC centres.",
        "official_url": "https://pmfby.gov.in/",
        "source_url": "https://agricoop.nic.in/en/pmfby",
        "helpline": "14447 / 1800-180-1551",
        "verification_source": "Department of Agriculture and Farmers Welfare, GoI",
        "is_active": True,
    },
    {
        "title": "KCC (Kisan Credit Card Scheme)",
        "slug": "kisan-credit-card",
        "short_description": "Flexible and affordable institutional credit up to ₹3 Lakh at an effective interest rate of just 4% for agriculture, allied activities, and animal husbandry.",
        "description": "The Kisan Credit Card (KCC) scheme provides farmers with timely and hassle-free short-term credit to meet cultivation expenses, post-harvest costs, produce marketing loan requirements, working capital for maintenance of farm assets, and allied agricultural activities like dairy, poultry, fisheries, and inland aquaculture. Under the Interest Subvention Scheme, farmers who repay promptly pay an interest rate as low as 4% per annum.",
        "category": "credit",
        "state": "All India",
        "farmer_type": "all",
        "min_age": 18,
        "max_age": 75,
        "gender": "any",
        "benefits": "• Revolving cash credit limit up to ₹3,00,000 at concessional interest rate of 7% (reduced to 4% with 3% prompt repayment subvention)\n• Collateral-free loan up to ₹1,60,000 (extended to ₹2,00,000 for tied loans via RBI guidelines)\n• ATM-enabled RuPay Kisan Card for easy cash withdrawal and merchant payments\n• Flexibility to draw and repay as per crop harvesting cycle\n• Includes built-in accidental insurance coverage up to ₹50,000",
        "eligibility": "• Individual or joint borrowers who are owner cultivators\n• Tenant farmers, oral lessees, and sharecroppers\n• Self Help Groups (SHGs) or Joint Liability Groups (JLGs) of farmers\n• Farmers involved in animal husbandry, poultry, and fisheries",
        "documents": "• Completed simplified KCC application form\n• Two passport size photographs\n• Proof of Identity: Aadhaar Card / Voter ID / Driving License\n• Proof of Address & Land Ownership documents verified by revenue authority\n• Sowing declaration showing cropped area",
        "application_process": "1. Download the one-page KCC application form from myscheme.gov.in or pmkisan.gov.in.\n2. Submit the form to your nearest public sector bank, RRB, cooperative bank, or through the CSC portal.\n3. Banks are mandated to issue the KCC within 14 working days of receiving completed application.\n4. RuPay debit card will be delivered to your address.",
        "official_url": "https://www.myscheme.gov.in/schemes/kcc",
        "source_url": "https://www.nabard.org/content1.aspx?id=594&catid=23&mid=530",
        "helpline": "1800-180-1551 / 1800-115-526",
        "verification_source": "Reserve Bank of India & NABARD",
        "is_active": True,
    },
    {
        "title": "PM-KUSUM (Kisan Urja Suraksha evam Utthaan Mahabhiyan)",
        "slug": "pm-kusum-solar-pump",
        "short_description": "Massive government subsidy of up to 60% to 90% for setting up solar irrigation pumps and solar power generation on barren farmlands.",
        "description": "PM-KUSUM is a transformational green energy initiative by the Ministry of New and Renewable Energy (MNRE). It empowers farmers to de-dieselise the farm sector by installing standalone solar-powered agriculture pumps (Component B), setting up grid-connected solar plants on uncultivated land for regular electricity sale income (Component A), and solarizing existing grid-connected electric pump sets (Component C).",
        "category": "subsidy",
        "state": "All India",
        "farmer_type": "all",
        "min_age": 18,
        "max_age": 100,
        "gender": "any",
        "benefits": "• Up to 60% standard subsidy (30% Central + 30% State Gov) on solar agriculture pumps (0.5 HP to 10 HP)\n• In North Eastern and Himalayan States, total subsidy reaches up to 80%–90%\n• Farmers only contribute 10%–20% of pump cost; remaining can be bank-financed\n• Zero recurring electricity bills and zero diesel expenditure\n• Steady extra income by selling surplus generated solar power back to the grid (DISCOM)",
        "eligibility": "• Individual farmers, groups of farmers, Water User Associations (WUAs), and Farmer Producer Organizations (FPOs)\n• Farmers having agricultural land without active grid electricity connection (for standalone pumps)\n• Farmers with existing electric connections wishing to solarize pumps",
        "documents": "• Aadhaar Card\n• Land Ownership record (Khasra/Khatauni)\n• Bank Account details\n• Declaration of water source availability (borewell / well / pond)\n• Passport size photographs",
        "application_process": "1. Visit the state-specific nodal agency portal via MNRE's PM-KUSUM portal (pmkusum.mnre.gov.in).\n2. Register online with Aadhaar and mobile number.\n3. Choose solar pump capacity (3 HP, 5 HP, 7.5 HP, etc.) and pump type (surface or submersible).\n4. Pay the farmer share (10%-20%) through online portal.\n5. Authorized vendor completes installation and water flow commissioning at your farm.",
        "official_url": "https://pmkusum.mnre.gov.in/",
        "source_url": "https://mnre.gov.in/solar/schemes/",
        "helpline": "1800-180-3333 / 011-24360707",
        "verification_source": "Ministry of New and Renewable Energy, GoI",
        "is_active": True,
    },
    {
        "title": "PMKSY (Pradhan Mantri Krishi Sinchayee Yojana - Per Drop More Crop)",
        "slug": "pm-krishi-sinchayee-yojana",
        "short_description": "45% to 55% capital subsidy on Drip and Sprinkler micro-irrigation systems to maximize water efficiency and crop yields.",
        "description": "Pradhan Mantri Krishi Sinchayee Yojana (PMKSY) – Per Drop More Crop is dedicated to enhancing water use efficiency at the farm level through micro-irrigation technologies. It encourages farmers to adopt precision drip irrigation and sprinkler systems, saving up to 50% water while increasing productivity by 20% to 35% through fertigation and targeted root hydration.",
        "category": "irrigation",
        "state": "All India",
        "farmer_type": "all",
        "min_age": 18,
        "max_age": 100,
        "gender": "any",
        "benefits": "• 55% financial assistance for Small & Marginal farmers\n• 45% financial assistance for other/large farmers\n• Additional top-up subsidies provided by several states (up to 70%-90% total subsidy)\n• Significant reduction in fertilizer consumption via fertigation\n• Saves labour and electric power while minimizing weed growth",
        "eligibility": "• All categories of farmers possessing cultivable land\n• Members of cooperative societies, SHGs, and registered farmer producer organizations\n• Must have an assured irrigation water source (borewell, canal, tube well, farm pond)",
        "documents": "• Aadhaar Card\n• Land registry document / 7/12 extract / Khatauni\n• Electricity bill of tube well or NOC for water source\n• Bank Passbook copy\n• Field map (Nazri Naksha)",
        "application_process": "1. Apply online via your State Agriculture / Horticulture Department portal (e.g., upagriculture.com in UP, mahadbt in Maharashtra).\n2. Select 'Micro Irrigation - Drip / Sprinkler'.\n3. Upload land records and choose registered drip manufacturing vendor.\n4. Department engineer inspects farm and releases work order.\n5. Subsidy is disbursed directly to farmer's account upon installation verification.",
        "official_url": "https://pmksy.gov.in/",
        "source_url": "https://agricoop.nic.in/en/pmksy",
        "helpline": "011-23383370 / 1800-180-1551",
        "verification_source": "Department of Agriculture & Farmers Welfare, GoI",
        "is_active": True,
    },
    {
        "title": "Soil Health Card Scheme (मृदा स्वास्थ्य कार्ड योजना)",
        "slug": "soil-health-card-scheme",
        "short_description": "100% free periodic soil nutrient test report with customized fertilizer dosage recommendations every two years.",
        "description": "The Soil Health Card (SHC) scheme is a national initiative to promote soil-test-based balanced nutrient management. Under this scheme, soil samples are systematically collected from farm plots and tested for 12 vital parameters: 3 Primary Nutrients (N, P, K), Secondary Nutrient (S), 5 Micronutrients (Zn, Fe, Cu, Mn, Bo), and Physical Parameters (pH, EC, Organic Carbon). Farmers receive a customized physical and digital health card with tailored fertilizer dosage.",
        "category": "subsidy",
        "state": "All India",
        "farmer_type": "all",
        "min_age": 18,
        "max_age": 100,
        "gender": "any",
        "benefits": "• 100% free testing at government soil testing laboratories\n• Reduces unnecessary expenditure on chemical fertilizers by 15% to 25%\n• Improves crop yield by 10% to 20% through targeted nutrient application\n• Card renewed every 2 years to track fertility improvements and soil health",
        "eligibility": "• All farmers owning or cultivating agricultural land in India\n• Applicable for all food crops, commercial crops, horticulture, and plantations",
        "documents": "• Aadhaar Card\n• Basic land identification (Khasra / Plot Number)\n• Mobile Number",
        "application_process": "1. Village Agricultural Assistant or Krishi Mitra collects GPS-tagged soil samples from your field.\n2. Sample is tested at the district Soil Testing Laboratory (STL).\n3. Download the digital Soil Health Card anytime from soilhealth.dac.gov.in by entering State, District, and Farmer Name or Khasra Number.\n4. Free printed cards are also distributed through Gram Panchayats.",
        "official_url": "https://soilhealth.dac.gov.in/",
        "source_url": "https://agricoop.nic.in/en/SoilHealth",
        "helpline": "011-24305948 / 1800-180-1551",
        "verification_source": "Ministry of Agriculture & Farmers Welfare, GoI",
        "is_active": True,
    },
    {
        "title": "SMAM (Sub-Mission on Agricultural Mechanization)",
        "slug": "sub-mission-agricultural-mechanization",
        "short_description": "40% to 50% subsidy on purchase of tractors, rotavators, power tillers, and up to 80% grant for Custom Hiring Centres.",
        "description": "Sub-Mission on Agricultural Mechanization (SMAM) aims to increase the reach of farm mechanization to small and marginal farmers and to regions with low power availability. It offers individual machinery purchase subsidies and financial assistance to rural youth and farmer groups to set up Custom Hiring Centres (CHCs), allowing farmers to rent heavy machinery affordably without high capital investment.",
        "category": "equipment",
        "state": "All India",
        "farmer_type": "all",
        "min_age": 18,
        "max_age": 100,
        "gender": "any",
        "benefits": "• 40% to 50% subsidy on individual modern farm implements (Tractors, Seed Drills, Harvesters, Power Weeders, Laser Levellers)\n• Higher subsidy percentage for SC, ST, women, and small/marginal farmers\n• Up to 80% project assistance (up to ₹10 Lakh to ₹40 Lakh) for establishing Custom Hiring Centres (CHCs)\n• Reduces manual drudgery and significantly expedites sowing, spraying, and harvesting operations",
        "eligibility": "• Individual farmers who have not availed equipment subsidy in the last 3-5 years\n• Cooperative societies, registered Farmer Producer Organizations (FPOs), Panchayats, and rural entrepreneurs for CHCs",
        "documents": "• Aadhaar Card\n• Land registry documents (Khatoni)\n• Bank Passbook copy\n• Caste Certificate (if claiming SC/ST subsidy benefits)\n• Driving License (for tractor subsidy applications)",
        "application_process": "1. Register on the central DBT Agrimachinery portal (agrimachinery.nic.in).\n2. Select Scheme: Sub-Mission on Agricultural Mechanization (SMAM).\n3. Choose equipment manufacturer and model from empaneled suppliers.\n4. Upload land and identity documents.\n5. Receive sanction letter, purchase from dealer, and get subsidy credited via DBT after physical verification.",
        "official_url": "https://agrimachinery.nic.in/",
        "source_url": "https://farmech.dac.gov.in/",
        "helpline": "1800-180-1551 / 011-23382937",
        "verification_source": "Mechanization & Technology Division, GoI",
        "is_active": True,
    },
    {
        "title": "PKVY (Paramparagat Krishi Vikas Yojana - Organic Farming)",
        "slug": "paramparagat-krishi-vikas-yojana",
        "short_description": "Financial assistance of ₹50,000 per hectare for cluster-based organic farming, bio-fertilizers, and PGS-India certification.",
        "description": "Paramparagat Krishi Vikas Yojana (PKVY) is an extended component of Soil Health Management under the National Mission on Sustainable Agriculture. It supports cluster-based traditional organic farming using indigenous practices, zero external chemical inputs, and Participatory Guarantee System (PGS-India) organic certification. It facilitates direct market linkages so farmers fetch premium prices for residue-free produce.",
        "category": "subsidy",
        "state": "All India",
        "farmer_type": "all",
        "min_age": 18,
        "max_age": 100,
        "gender": "any",
        "benefits": "• Total financial assistance of ₹50,000 per hectare over a 3-year period\n• ₹31,000/ha provided directly to farmers via DBT for organic seeds, bio-fertilizers, bio-pesticides, vermicompost, and botanical extracts\n• ₹8,800/ha allocated for value addition, packaging, labelling, and organic branding\n• Free PGS-India organic certification without expensive third-party inspection agencies",
        "eligibility": "• Farmers forming clusters of 20 or more farmers with a total contiguous area of 20 hectares or 50 acres\n• Ready to commit to non-chemical farming methods\n• Open to small, marginal, and tenant farmers",
        "documents": "• Aadhaar Card\n• Land ownership / Lease proof\n• Bank Account details linked with Aadhaar\n• Cluster resolution signed by member farmers",
        "application_process": "1. Approach the local Block Agricultural Officer or Regional Council for PGS-India.\n2. Form a farmer cluster of at least 20 members (or join an existing active cluster).\n3. Register cluster details on the PGS-India portal (pgsindia-ncof.gov.in).\n4. Undergo training and peer inspection visits.\n5. Funds are released directly into cluster member accounts in 3 phased installments.",
        "official_url": "https://pgsindia-ncof.gov.in/",
        "source_url": "https://agricoop.nic.in/en/pkvy",
        "helpline": "0120-2764906 / 1800-180-1551",
        "verification_source": "National Centre of Organic and Natural Farming, GoI",
        "is_active": True,
    },
    {
        "title": "PM-KMY (Pradhan Mantri Kisan Maan-Dhan Yojana)",
        "slug": "pm-kisan-maan-dhan-yojana",
        "short_description": "Guaranteed monthly old-age pension of ₹3,000 for small and marginal farmers after attaining 60 years of age.",
        "description": "Pradhan Mantri Kisan Maan-Dhan Yojana (PM-KMY) is an old-age social security pension scheme for Small and Marginal Farmers (SMFs). It is a voluntary, contributory pension scheme managed by the Life Insurance Corporation of India (LIC). Farmers contribute a small monthly amount between ₹55 to ₹200 (depending on entry age 18-40), with an equal 100% matching contribution deposited by the Central Government.",
        "category": "income",
        "state": "All India",
        "farmer_type": "small",
        "min_age": 18,
        "max_age": 40,
        "gender": "any",
        "benefits": "• Assured monthly pension of ₹3,000 for life on reaching 60 years of age\n• 50% family pension (₹1,500/month) for spouse in case of subscriber's demise\n• Central Government deposits 100% equal matching contribution every month\n• Monthly contribution can be directly auto-debited from PM-KISAN quarterly installments",
        "eligibility": "• Small and Marginal farmers having cultivable landholding up to 2 hectares (5 acres)\n• Entry age between 18 and 40 years\n• Must not be covered under other statutory social security schemes (NPS, ESIC, EPFO)",
        "documents": "• Aadhaar Card\n• Savings Bank Account passbook or Jan Dhan account details\n• Land ownership documents (Khasra/Khatauni)",
        "application_process": "1. Visit the nearest Common Service Centre (CSC) or visit maandhan.in.\n2. Provide Aadhaar number, bank account details, and PM-KISAN beneficiary ID.\n3. Initial monthly contribution is debited in cash or from bank account.\n4. Sign auto-debit consent form.\n5. Unique Pension Pay Order (Kisan Pension Card) is generated instantly.",
        "official_url": "https://maandhan.in/",
        "source_url": "https://agricoop.nic.in/en/pm-kmy",
        "helpline": "1800-267-6888 / 14434",
        "verification_source": "Department of Agriculture & Farmers Welfare & LIC",
        "is_active": True,
    },
    {
        "title": "AIF (Agriculture Infrastructure Fund)",
        "slug": "agriculture-infrastructure-fund",
        "short_description": "Medium-long term loans with 3% interest subvention and credit guarantee up to ₹2 Crore for farm post-harvest infrastructure.",
        "description": "The Agriculture Infrastructure Fund (AIF) is a dedicated financing facility providing ₹1 Lakh Crore to develop post-harvest management infrastructure and community farming assets. It empowers farmers, Agri-entrepreneurs, startups, and FPOs to construct modern warehouses, silos, pack houses, cold storage facilities, primary processing centers, and sorting/grading lines to reduce post-harvest losses.",
        "category": "credit",
        "state": "All India",
        "farmer_type": "all",
        "min_age": 21,
        "max_age": 70,
        "gender": "any",
        "benefits": "• 3% per annum interest subvention on bank loans up to ₹2 Crore for a maximum of 7 years\n• Credit Guarantee coverage under CGTMSE for loans up to ₹2 Crore with government-paid fee\n• Moratorium on loan repayment ranges from 6 months up to a generous 2 years\n• Convergence allowed with all other Central and State capital subsidy schemes",
        "eligibility": "• Primary Agricultural Credit Societies (PACS), Marketing Cooperative Societies\n• Farmer Producer Organizations (FPOs), Self Help Groups (SHGs)\n• Individual Farmers, Joint Liability Groups, and Agricultural Entrepreneurs\n• Startups and state-sponsored public-private partnership projects",
        "documents": "• Project Detailed Project Report (DPR)\n• Land records or lease agreement for project site (minimum 10-15 years lease)\n• KYC Documents: Aadhaar, PAN Card\n• Bank statements for the last 6-12 months\n• Quotations/estimates of machinery and civil works",
        "application_process": "1. Register as a Beneficiary on the AIF Portal (agriinfra.dac.gov.in).\n2. Fill project proposal, specify required loan amount, and upload the DPR.\n3. Choose preferred lending bank from the empaneled list of scheduled commercial banks.\n4. Ministry evaluates and sanctions in-principle approval within 7 days.\n5. Bank processes and disburses loan with automatically applied 3% interest subvention.",
        "official_url": "https://agriinfra.dac.gov.in/",
        "source_url": "https://agricoop.nic.in/en/aif",
        "helpline": "011-23381012 / 1800-180-1551",
        "verification_source": "Ministry of Agriculture & Farmers Welfare, GoI",
        "is_active": True,
    },
    {
        "title": "National Beekeeping & Honey Mission (NBHM - Mithi Kranti)",
        "slug": "national-beekeeping-honey-mission",
        "short_description": "Up to 80% subsidy for scientific beekeeping, beehive boxes, honey processing, and lab testing to boost secondary farm income.",
        "description": "The National Beekeeping & Honey Mission (NBHM) is implemented under the Atmanirbhar Bharat Abhiyan for the overall promotion and development of scientific beekeeping to achieve the goal of 'Sweet Revolution' (Mithi Kranti). Honeybees provide pollination support that increases crop yields by 20%-40% while generating lucrative side income from honey, beeswax, propolis, royal jelly, and bee venom.",
        "category": "subsidy",
        "state": "All India",
        "farmer_type": "all",
        "min_age": 18,
        "max_age": 100,
        "gender": "any",
        "benefits": "• Up to 80% subsidy on procurement of bee colonies, hives, and beekeeping equipment\n• Subsidies up to ₹20 Lakh to ₹50 Lakh for setting up honey extraction, testing labs, and processing units\n• Free comprehensive scientific beekeeping training through National Bee Board (NBB)\n• Boosts farm crop pollination and significantly enhances harvest quality",
        "eligibility": "• Individual farmers, beekeepers, rural youths, and women SHGs\n• Farmer Producer Organizations (FPOs) and Beekeeping Cooperatives\n• Suitable for farmers with mustard, sunflower, litchi, apple, eucalyptus, or flora surroundings",
        "documents": "• Aadhaar Card\n• Bank Account details\n• Certificate of Training in Beekeeping (from KVK or recognized institute)\n• Land record or permission letter from orchard/field owner",
        "application_process": "1. Complete registration on the Madhukranti Portal (nbhm.gov.in) and obtain National Bee Board (NBB) membership ID.\n2. Submit project proposal for beehive unit or processing plant.\n3. State Horticulture Mission inspects and recommends application.\n4. Subsidy is transferred directly via DBT.",
        "official_url": "https://nbhm.gov.in/",
        "source_url": "https://nbb.gov.in/",
        "helpline": "011-23389012 / 011-23382012",
        "verification_source": "National Bee Board (NBB), GoI",
        "is_active": True,
    },
    {
        "title": "MIDH (Mission for Integrated Development of Horticulture)",
        "slug": "mission-integrated-development-horticulture",
        "short_description": "50% capital subsidy for greenhouses, shade net houses, plastic mulching, and high-density fruit orchard cultivation.",
        "description": "Mission for Integrated Development of Horticulture (MIDH) is a Centrally Sponsored Scheme for holistic growth of the horticulture sector covering fruits, vegetables, root and tuber crops, mushrooms, spices, flowers, aromatic plants, and coconut. It provides extensive capital assistance for protected cultivation (polyhouse, shade net), high-quality planting material, mushroom production units, pack houses, and cold rooms.",
        "category": "subsidy",
        "state": "All India",
        "farmer_type": "all",
        "min_age": 18,
        "max_age": 100,
        "gender": "any",
        "benefits": "• 50% subsidy on cost of tubular structure Polyhouse and Net Shade House\n• Up to 50% financial assistance for establishing new orchards of mango, guava, citrus, pomegranate, and apple\n• 40% subsidy for refrigerated transport vans, solar cold rooms, and packhouses\n• High income per square meter through year-round off-season vegetable cultivation",
        "eligibility": "• All farmers and groups of farmers owning suitable agricultural land with irrigation access\n• FPOs, horticulture cooperatives, and agricultural graduates",
        "documents": "• Aadhaar Card\n• Land Records (Khasra, Khatauni) verified by Tehsildar\n• Detailed quotation from certified structural polyhouse manufacturer\n• Soil and water testing reports\n• Bank Passbook copy",
        "application_process": "1. Apply online via your State Horticulture Department portal (MIDH module).\n2. Submit farm land details and proposed horticulture structure specification.\n3. District Horticulture Officer (DHO) conducts pre-inspection.\n4. Complete construction with approved manufacturer; subsidy disbursed after geo-tagged post-inspection.",
        "official_url": "https://midh.gov.in/",
        "source_url": "https://hortnet.gov.in/",
        "helpline": "011-23383802 / 1800-180-1551",
        "verification_source": "Horticulture Division, MoA&FW, GoI",
        "is_active": True,
    },
    {
        "title": "e-NAM (National Agriculture Market)",
        "slug": "enam-national-agriculture-market",
        "short_description": "Pan-India electronic trading portal connecting APMC mandis to give farmers maximum prices and direct online payments.",
        "description": "National Agriculture Market (e-NAM) is a pan-India electronic trading portal that networks existing APMC mandis to create a unified national market for agricultural commodities. It eliminates middlemen exploitation, provides transparent online price discovery based on actual quality assaying, offers weighing assurance, and facilitates instant direct online payment into farmers' bank accounts.",
        "category": "other",
        "state": "All India",
        "farmer_type": "all",
        "min_age": 18,
        "max_age": 100,
        "gender": "any",
        "benefits": "• Access to thousands of competitive traders and buyers across India from your local mandi\n• Transparent electronic bidding ensures 10% to 20% higher produce price realization\n• Free scientific assaying (quality testing) of crop samples before auction\n• Immediate online payments directly transferred to bank accounts (zero cash delays)\n• Integrated warehousing receipts (e-NWR) to pledge stock and take low-interest credit",
        "eligibility": "• All farmers who wish to sell notified agricultural produce\n• Available across 1,361+ integrated mandis in 27 States and Union Territories",
        "documents": "• Aadhaar Card\n• Bank Passbook (for receiving sale proceeds)\n• Active Mobile Number for receiving SMS auction alerts",
        "application_process": "1. Register online on enam.gov.in or download the e-NAM Mobile App.\n2. Or bring your harvest produce to your nearest e-NAM enabled APMC Mandi gate.\n3. Mandi gate operator generates e-lot number and staff collects sample for quality testing.\n4. Traders across India bid online; farmer accepts best bid on their phone.\n5. Payment is credited directly into bank account via RTGS/NEFT.",
        "official_url": "https://www.enam.gov.in/",
        "source_url": "https://agricoop.nic.in/en/e-NAM",
        "helpline": "1800-270-0224 / 011-26862367",
        "verification_source": "Small Farmers' Agri-Business Consortium (SFAC), GoI",
        "is_active": True,
    },
    {
        "title": "National Livestock Mission (NLM - Dairy & Poultry Subsidy)",
        "slug": "national-livestock-mission",
        "short_description": "50% capital subsidy up to ₹50 Lakh for establishing rural poultry farms, sheep/goat breeding, and fodder production units.",
        "description": "The National Livestock Mission (NLM) was launched by the Department of Animal Husbandry & Dairying to promote entrepreneurship, breed improvement, and modern infrastructure in small ruminants, poultry, piggery, and animal fodder development. It offers huge capital subsidies to farmers and rural entrepreneurs looking to scale commercial animal farming.",
        "category": "subsidy",
        "state": "All India",
        "farmer_type": "all",
        "min_age": 18,
        "max_age": 65,
        "gender": "any",
        "benefits": "• 50% capital subsidy (up to ₹25 Lakh for poultry, ₹50 Lakh for sheep/goat/pig breeding units)\n• 50% subsidy up to ₹50 Lakh for fodder seed processing and silage making units\n• Subsidies are back-ended and disbursed in two equal installments\n• Diversifies farm income and builds resilience against crop failure",
        "eligibility": "• Individual farmers, entrepreneurs, SHGs, JLGs, and FPOs\n• Must have suitable land (owned or leased for at least 10 years)\n• Relevant experience or training certificate in animal husbandry/poultry",
        "documents": "• Detailed Project Report (DPR) with cash-flow projection\n• Aadhaar Card & PAN Card\n• Land ownership deed or registered lease agreement\n• Bank sanction letter or net worth proof\n• Animal Husbandry training certificate",
        "application_process": "1. Apply online via the NLM Udyami Mitra portal (nlm.udyamimitra.in).\n2. Upload DPR and land documents.\n3. State Level Executive Committee (SLEC) inspects and approves proposal.\n4. Loan is sanctioned by bank and first 50% subsidy installment is deposited in subsidy reserve fund.",
        "official_url": "https://nlm.udyamimitra.in/",
        "source_url": "https://dahd.nic.in/schemes/programmes/national_livestock_mission",
        "helpline": "011-23384509 / 1800-180-1551",
        "verification_source": "Department of Animal Husbandry & Dairying, GoI",
        "is_active": True,
    },
    {
        "title": "RKVY-RAFTAAR (Agripreneurship & Startup Grant)",
        "slug": "rashtriya-krishi-vikas-yojana",
        "short_description": "Grant-in-aid up to ₹25 Lakh for innovative agriculture startups, farm youth ventures, and FPO processing infrastructure.",
        "description": "Rashtriya Krishi Vikas Yojana - Remunerative Approaches for Agriculture and Allied Sector Rejuvenation (RKVY-RAFTAAR) incubates and finances agri-startups, young farmer innovators, and rural agribusiness enterprises. Under the Innovation and Agri-entrepreneurship component, farmers with innovative product/farming concepts receive mentorship, incubation at premier agricultural institutes (IARI, IITs, SAUs), and non-repayable seed funding grants.",
        "category": "subsidy",
        "state": "All India",
        "farmer_type": "all",
        "min_age": 18,
        "max_age": 60,
        "gender": "any",
        "benefits": "• Idea Stage Grant (Idea to Prototype): Up to ₹5 Lakh grant with 2 months training\n• Seed Stage Grant (Early stage to Market): Up to ₹25 Lakh grant-in-aid (85% grant, 15% entrepreneur contribution)\n• Access to top-tier university labs, mentor networks, and investor pitching sessions\n• 100% intellectual property rights retained by farmer-innovator",
        "eligibility": "• Individual farmers, agricultural innovators, farm youth, and early-stage agri-startups\n• Concept must be related to agriculture, precision farming, post-harvesting, agritech, dairy, or agro-processing",
        "documents": "• Pitch deck explaining problem, agricultural solution, and commercial roadmap\n• Aadhaar & PAN Card\n• Company/Partnership incorporation certificate (if already registered)\n• Bank account details",
        "application_process": "1. Apply through knowledge partner portals (e.g. Pusa Krishi IARI, MANAGE Hyderabad, CCSHAU Hisar).\n2. Shortlisted applicants attend an intense 2-month incubation bootcamp.\n3. Present before the Rice / Seed Evaluation Committee.\n4. Grant disbursed in milestone tranches directly to recipient bank accounts.",
        "official_url": "https://rkvy.nic.in/",
        "source_url": "https://agricoop.nic.in/en/rkvy",
        "helpline": "011-23382444 / 1800-180-1551",
        "verification_source": "RKVY Division, Ministry of Agriculture & Farmers Welfare",
        "is_active": True,
    },
]


class Command(BaseCommand):
    help = "Seeds comprehensive Indian government agriculture schemes into the database."

    def handle(self, *args, **options):
        self.stdout.write(self.style.NOTICE("Seeding Government Schemes..."))
        created_count = 0
        updated_count = 0

        for data in SCHEMES_DATA:
            slug = data["slug"]
            scheme, created = GovernmentScheme.objects.update_or_create(
                slug=slug,
                defaults={
                    "title": data["title"],
                    "short_description": data["short_description"],
                    "description": data["description"],
                    "category": data["category"],
                    "state": data["state"],
                    "farmer_type": data["farmer_type"],
                    "min_age": data.get("min_age", 18),
                    "max_age": data.get("max_age", 100),
                    "gender": data.get("gender", "any"),
                    "benefits": data["benefits"],
                    "eligibility": data["eligibility"],
                    "documents": data["documents"],
                    "application_process": data["application_process"],
                    "official_url": data["official_url"],
                    "source_url": data["source_url"],
                    "helpline": data["helpline"],
                    "verification_source": data["verification_source"],
                    "is_active": data["is_active"],
                    "valid_from": date(2020, 1, 1),
                }
            )
            if created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Successfully seeded schemes! Created: {created_count}, Updated: {updated_count}, Total: {GovernmentScheme.objects.count()}"
            )
        )
