# Generated by Django 5.2.17 on 2026-10-01 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_type", models.CharField(max_length=50)),
                ("message", models.TextField()),
                (
                    "sent_via",
                    models.CharField(
                        choices=[("SMS", "SMS"), ("WhatsApp", "WhatsApp")],
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="Sent", max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlertPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Phone number for SMS/WhatsApp alerts",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "weather_alerts",
                    models.BooleanField(
                        default=True,
                        help_text="Extreme weather warnings (rain, frost, etc.)",
                    ),
                ),
                (
                    "mandi_alerts",
                    models.BooleanField(
                        default=False, help_text="Price spikes for your crops"
                    ),
                ),
                (
                    "disease_alerts",
                    models.BooleanField(
                        default=True,
                        help_text="Disease outbreak warnings in your district",
                    ),
                ),
                (
                    "irrigation_alerts",
                    models.BooleanField(
                        default=False, help_text="Irrigation & soil moisture reminders"
                    ),
                ),
                (
                    "scheme_alerts",
                    models.BooleanField(
                        default=True, help_text="Government scheme deadlines"
                    ),
                ),
                ("whatsapp_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
